name: Our Deployment
on:
  push:
    branches: [main]
jobs:
  deploy-dev:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v3
      - name: set up node
        uses: actions/setup-node@v3
        
        # node-version-file: ".nvmrc" -> node-version: 22
        with:
          node-version: 22
          cache: npm
      - name: install
        run: npm ci
      - name: test
        run: npm test
      - name: build
        run: npm run build
      - name: deploy
        run: npm run deploy

  deploy-qa:
    needs: [deploy-dev]
    environment: qa
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v3
      - name: set up node
        uses: actions/setup-node@v3
        # node-version-file: ".nvmrc" -> node-version: 22
        with:
          node-version: 22
          cache: npm
      - name: install
        run: npm ci
      - name: test
        run: npm test
      - name: build
        run: npm run build
      - name: deploy
        run: npm run deploy

  deploy-prod:
    needs: [deploy-qa]
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v3
      - name: set up node
        uses: actions/setup-node@v3
        # node-version-file: ".nvmrc" -> node-version: 22
        with:
          node-version: 22
          cache: npm
      - name: install
        run: npm ci
      - name: test
        run: npm test
      - name: build
        run: npm run build
      - name: deploy
        run: npm run deploy
      - name: notify
        run: echo 'Deployment completed in prod! 🎉'